[package]
name = "rusty-lox"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
float-cmp = "0.9.0"
wasm-encoder = "0.3"
clap = { version = "3.1.8", features = ["derive"] }

[dev-dependencies]
claim = "0.5.0"