[package]
name = "rusty-lox"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
thiserror = "1.0.64"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
